# Generated by Django 4.0.5 on 2025-03-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='default@example.com', max_length=100),
            preserve_default=False,
        ),
    ]
